-- ============================================================
-- 013_phase1_gems.sql — 阶段1 四色宝石 + 宝石合成链数据（1-5 / 1-6）
-- ============================================================
-- 来源：ARPG系统移植计划书.md 阶段 1（1-5 四色宝石 / 1-6 宝石书合成链）
-- 目标库：tw_world ｜ 幂等：REPLACE
-- 映射（5 级 → 原版 SpellItemEnchantment 属性附魔 +1~+5）：
--   红宝石(力量) 68/69/70/106/107  黄宝石(智力) 79/80/81/94/95
--   绿宝石(敏捷) 74/75/76/90/91    紫宝石(耐力) 71/72/73/102/103
-- 效果实现：gem.lua 右键给装备 PROP 槽3 打附魔（EQUIP_SPELL 自动生效/重登恢复）
-- ============================================================

-- 建 1 级宝石（红=Star Ruby 7910 / 黄=Citrine 3864 / 绿=Jade 1529 / 紫=Large Opal 12799）
REPLACE INTO `item_template`
SELECT 901001, class, subclass, '红宝石', '右键镶嵌到装备，+1 力量（同色最多 2 颗）', 4777, 2, flags, buy_count, 0, 0, inventory_type, allowable_class, allowable_race, item_level, required_level, required_skill, required_skill_rank, required_spell, required_honor_rank, required_city_rank, required_reputation_faction, required_reputation_rank, 20, stackable, container_slots, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, stat_type4, stat_value4, stat_type5, stat_value5, stat_type6, stat_value6, stat_type7, stat_value7, stat_type8, stat_value8, stat_type9, stat_value9, stat_type10, stat_value10, delay, range_mod, ammo_type, dmg_min1, dmg_max1, dmg_type1, dmg_min2, dmg_max2, dmg_type2, dmg_min3, dmg_max3, dmg_type3, dmg_min4, dmg_max4, dmg_type4, dmg_min5, dmg_max5, dmg_type5, block, armor, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, 0, 0, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, 0, 0, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, 0, 0, spellcharges_3, spellppmrate_3, spellcooldown_3, spellcategory_3, spellcategorycooldown_3, 0, 0, spellcharges_4, spellppmrate_4, spellcooldown_4, spellcategory_4, spellcategorycooldown_4, 0, 0, spellcharges_5, spellppmrate_5, spellcooldown_5, spellcategory_5, spellcategorycooldown_5, 0, page_text, page_language, page_material, start_quest, lock_id, material, sheath, 0, set_id, max_durability, area_bound, map_bound, duration, bag_family, disenchant_id, food_type, 0, 0, wrapped_gift, extra_flags, other_team_entry, script_name
FROM `item_template` WHERE entry = 7910;
REPLACE INTO `item_template`
SELECT 901006, class, subclass, '黄宝石', '右键镶嵌到装备，+1 智力（同色最多 2 颗）', 7339, 2, flags, buy_count, 0, 0, inventory_type, allowable_class, allowable_race, item_level, required_level, required_skill, required_skill_rank, required_spell, required_honor_rank, required_city_rank, required_reputation_faction, required_reputation_rank, 20, stackable, container_slots, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, stat_type4, stat_value4, stat_type5, stat_value5, stat_type6, stat_value6, stat_type7, stat_value7, stat_type8, stat_value8, stat_type9, stat_value9, stat_type10, stat_value10, delay, range_mod, ammo_type, dmg_min1, dmg_max1, dmg_type1, dmg_min2, dmg_max2, dmg_type2, dmg_min3, dmg_max3, dmg_type3, dmg_min4, dmg_max4, dmg_type4, dmg_min5, dmg_max5, dmg_type5, block, armor, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, 0, 0, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, 0, 0, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, 0, 0, spellcharges_3, spellppmrate_3, spellcooldown_3, spellcategory_3, spellcategorycooldown_3, 0, 0, spellcharges_4, spellppmrate_4, spellcooldown_4, spellcategory_4, spellcategorycooldown_4, 0, 0, spellcharges_5, spellppmrate_5, spellcooldown_5, spellcategory_5, spellcategorycooldown_5, 0, page_text, page_language, page_material, start_quest, lock_id, material, sheath, 0, set_id, max_durability, area_bound, map_bound, duration, bag_family, disenchant_id, food_type, 0, 0, wrapped_gift, extra_flags, other_team_entry, script_name
FROM `item_template` WHERE entry = 3864;
REPLACE INTO `item_template`
SELECT 901011, class, subclass, '绿宝石', '右键镶嵌到装备，+1 敏捷（同色最多 2 颗）', 1262, 2, flags, buy_count, 0, 0, inventory_type, allowable_class, allowable_race, item_level, required_level, required_skill, required_skill_rank, required_spell, required_honor_rank, required_city_rank, required_reputation_faction, required_reputation_rank, 20, stackable, container_slots, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, stat_type4, stat_value4, stat_type5, stat_value5, stat_type6, stat_value6, stat_type7, stat_value7, stat_type8, stat_value8, stat_type9, stat_value9, stat_type10, stat_value10, delay, range_mod, ammo_type, dmg_min1, dmg_max1, dmg_type1, dmg_min2, dmg_max2, dmg_type2, dmg_min3, dmg_max3, dmg_type3, dmg_min4, dmg_max4, dmg_type4, dmg_min5, dmg_max5, dmg_type5, block, armor, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, 0, 0, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, 0, 0, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, 0, 0, spellcharges_3, spellppmrate_3, spellcooldown_3, spellcategory_3, spellcategorycooldown_3, 0, 0, spellcharges_4, spellppmrate_4, spellcooldown_4, spellcategory_4, spellcategorycooldown_4, 0, 0, spellcharges_5, spellppmrate_5, spellcooldown_5, spellcategory_5, spellcategorycooldown_5, 0, page_text, page_language, page_material, start_quest, lock_id, material, sheath, 0, set_id, max_durability, area_bound, map_bound, duration, bag_family, disenchant_id, food_type, 0, 0, wrapped_gift, extra_flags, other_team_entry, script_name
FROM `item_template` WHERE entry = 1529;
REPLACE INTO `item_template`
SELECT 901016, class, subclass, '紫宝石', '右键镶嵌到装备，+1 耐力（同色最多 2 颗）', 6496, 2, flags, buy_count, 0, 0, inventory_type, allowable_class, allowable_race, item_level, required_level, required_skill, required_skill_rank, required_spell, required_honor_rank, required_city_rank, required_reputation_faction, required_reputation_rank, 20, stackable, container_slots, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, stat_type4, stat_value4, stat_type5, stat_value5, stat_type6, stat_value6, stat_type7, stat_value7, stat_type8, stat_value8, stat_type9, stat_value9, stat_type10, stat_value10, delay, range_mod, ammo_type, dmg_min1, dmg_max1, dmg_type1, dmg_min2, dmg_max2, dmg_type2, dmg_min3, dmg_max3, dmg_type3, dmg_min4, dmg_max4, dmg_type4, dmg_min5, dmg_max5, dmg_type5, block, armor, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, 0, 0, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, 0, 0, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, 0, 0, spellcharges_3, spellppmrate_3, spellcooldown_3, spellcategory_3, spellcategorycooldown_3, 0, 0, spellcharges_4, spellppmrate_4, spellcooldown_4, spellcategory_4, spellcategorycooldown_4, 0, 0, spellcharges_5, spellppmrate_5, spellcooldown_5, spellcategory_5, spellcategorycooldown_5, 0, page_text, page_language, page_material, start_quest, lock_id, material, sheath, 0, set_id, max_durability, area_bound, map_bound, duration, bag_family, disenchant_id, food_type, 0, 0, wrapped_gift, extra_flags, other_team_entry, script_name
FROM `item_template` WHERE entry = 12799;

-- 派生 2~5 级（红 901002-005 / 黄 901007-010 / 绿 901012-015 / 紫 901017-020）
INSERT IGNORE INTO `item_template`
SELECT entry+1, class, subclass, name, description, display_id, quality, flags, buy_count, buy_price, sell_price, inventory_type, allowable_class, allowable_race, item_level, required_level, required_skill, required_skill_rank, required_spell, required_honor_rank, required_city_rank, required_reputation_faction, required_reputation_rank, max_count, stackable, container_slots, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, stat_type4, stat_value4, stat_type5, stat_value5, stat_type6, stat_value6, stat_type7, stat_value7, stat_type8, stat_value8, stat_type9, stat_value9, stat_type10, stat_value10, delay, range_mod, ammo_type, dmg_min1, dmg_max1, dmg_type1, dmg_min2, dmg_max2, dmg_type2, dmg_min3, dmg_max3, dmg_type3, dmg_min4, dmg_max4, dmg_type4, dmg_min5, dmg_max5, dmg_type5, block, armor, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, spellid_3, spelltrigger_3, spellcharges_3, spellppmrate_3, spellcooldown_3, spellcategory_3, spellcategorycooldown_3, spellid_4, spelltrigger_4, spellcharges_4, spellppmrate_4, spellcooldown_4, spellcategory_4, spellcategorycooldown_4, spellid_5, spelltrigger_5, spellcharges_5, spellppmrate_5, spellcooldown_5, spellcategory_5, spellcategorycooldown_5, bonding, page_text, page_language, page_material, start_quest, lock_id, material, sheath, random_property, set_id, max_durability, area_bound, map_bound, duration, bag_family, disenchant_id, food_type, min_money_loot, max_money_loot, wrapped_gift, extra_flags, other_team_entry, script_name
FROM `item_template`
WHERE entry IN (901001,901006,901011,901016)
  AND entry+1 NOT IN (SELECT entry FROM item_template);

-- 宝石恢复使用法术（客户端可右键触发，脚本 return false 阻止）+ 品质/命名
UPDATE `item_template` SET spellid_1=8690, spelltrigger_1=0 WHERE entry BETWEEN 901001 AND 901020;
UPDATE `item_template` SET name='完美红宝石', quality=3 WHERE entry=901002;
UPDATE `item_template` SET name='贵族红宝石', quality=4 WHERE entry=901003;
UPDATE `item_template` SET name='帝国红宝石', quality=4 WHERE entry=901004;
UPDATE `item_template` SET name='皇家红宝石', quality=4 WHERE entry=901005;
UPDATE `item_template` SET name='完美黄宝石', quality=3 WHERE entry=901007;
UPDATE `item_template` SET name='贵族黄宝石', quality=4 WHERE entry=901008;
UPDATE `item_template` SET name='帝国黄宝石', quality=4 WHERE entry=901009;
UPDATE `item_template` SET name='皇家黄宝石', quality=4 WHERE entry=901010;
UPDATE `item_template` SET name='完美绿宝石', quality=3 WHERE entry=901012;
UPDATE `item_template` SET name='贵族绿宝石', quality=4 WHERE entry=901013;
UPDATE `item_template` SET name='帝国绿宝石', quality=4 WHERE entry=901014;
UPDATE `item_template` SET name='皇家绿宝石', quality=4 WHERE entry=901015;
UPDATE `item_template` SET name='完美紫宝石', quality=3 WHERE entry=901017;
UPDATE `item_template` SET name='贵族紫宝石', quality=4 WHERE entry=901018;
UPDATE `item_template` SET name='帝国紫宝石', quality=4 WHERE entry=901019;
UPDATE `item_template` SET name='皇家紫宝石', quality=4 WHERE entry=901020;

-- 书页/书（1-6 合成链，复制 7910 模板）
REPLACE INTO `item_template`
SELECT 905002, class, subclass, '宝石书页', '宝石书碎片，集齐 3 页合成 1 本宝石书。', 4777, 1, flags, buy_count, 0, 0, inventory_type, allowable_class, allowable_race, item_level, required_level, required_skill, required_skill_rank, required_spell, required_honor_rank, required_city_rank, required_reputation_faction, required_reputation_rank, 50, stackable, container_slots, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, stat_type4, stat_value4, stat_type5, stat_value5, stat_type6, stat_value6, stat_type7, stat_value7, stat_type8, stat_value8, stat_type9, stat_value9, stat_type10, stat_value10, delay, range_mod, ammo_type, dmg_min1, dmg_max1, dmg_type1, dmg_min2, dmg_max2, dmg_type2, dmg_min3, dmg_max3, dmg_type3, dmg_min4, dmg_max4, dmg_type4, dmg_min5, dmg_max5, dmg_type5, block, armor, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, 8690, 0, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, 0, 0, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, 0, 0, spellcharges_3, spellppmrate_3, spellcooldown_3, spellcategory_3, spellcategorycooldown_3, 0, 0, spellcharges_4, spellppmrate_4, spellcooldown_4, spellcategory_4, spellcategorycooldown_4, 0, 0, spellcharges_5, spellppmrate_5, spellcooldown_5, spellcategory_5, spellcategorycooldown_5, 0, page_text, page_language, page_material, start_quest, lock_id, material, sheath, 0, set_id, max_durability, area_bound, map_bound, duration, bag_family, disenchant_id, food_type, 0, 0, wrapped_gift, extra_flags, other_team_entry, script_name
FROM `item_template` WHERE entry = 7910;
REPLACE INTO `item_template`
SELECT 905003, class, subclass, '宝石书', '右键打开，兑换 1 颗随机 1 级四色宝石。', 4777, 2, flags, buy_count, 0, 0, inventory_type, allowable_class, allowable_race, item_level, required_level, required_skill, required_skill_rank, required_spell, required_honor_rank, required_city_rank, required_reputation_faction, required_reputation_rank, 20, stackable, container_slots, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, stat_type4, stat_value4, stat_type5, stat_value5, stat_type6, stat_value6, stat_type7, stat_value7, stat_type8, stat_value8, stat_type9, stat_value9, stat_type10, stat_value10, delay, range_mod, ammo_type, dmg_min1, dmg_max1, dmg_type1, dmg_min2, dmg_max2, dmg_type2, dmg_min3, dmg_max3, dmg_type3, dmg_min4, dmg_max4, dmg_type4, dmg_min5, dmg_max5, dmg_type5, block, armor, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, 8690, 0, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, 0, 0, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, 0, 0, spellcharges_3, spellppmrate_3, spellcooldown_3, spellcategory_3, spellcategorycooldown_3, 0, 0, spellcharges_4, spellppmrate_4, spellcooldown_4, spellcategory_4, spellcategorycooldown_4, 0, 0, spellcharges_5, spellppmrate_5, spellcooldown_5, spellcategory_5, spellcategorycooldown_5, 0, page_text, page_language, page_material, start_quest, lock_id, material, sheath, 0, set_id, max_durability, area_bound, map_bound, duration, bag_family, disenchant_id, food_type, 0, 0, wrapped_gift, extra_flags, other_team_entry, script_name
FROM `item_template` WHERE entry = 7910;
